# Generated by Django 2.2.2 on 2019-06-09 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = [
  ]

  operations = [
    migrations.CreateModel(
      name='Question',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('question_text', models.CharField(max_length=600)),
        ('exam', models.CharField(max_length=100)),
      ],
    ),
    migrations.CreateModel(
      name='Answer',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('answer_text', models.CharField(max_length=600)),
        ('correct', models.BooleanField(default=False)),
        ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
      ],
    ),
  ]
