# Generated by Django 2.2.2 on 2019-06-09 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('questions', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='Exam',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('exam_name', models.CharField(max_length=50)),
      ],
    ),
    migrations.AlterField(
      model_name='question',
      name='exam',
      field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Exam'),
    ),
  ]
