# Generated by Django 2.2.2 on 2019-06-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('questions', '0002_auto_20190609_1847'),
  ]

  operations = [
    migrations.AddField(
      model_name='exam',
      name='active',
      field=models.BooleanField(default=True),
    ),
  ]
